services:
  db:
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: .
    working_dir: /app/
    command:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate --noinput
        python manage.py update_index
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db:db
    env_file:
      - .env
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY="${SECRET_KEY}"
    depends_on:
      - db
